url: "http://kylase.github.com/CircosAPI"

name: "CircosAPI"
description: "CircosAPI for CIRCOS Data Visualization"

markdown: rdiscount
permalink: pretty
pygments: true

analytics: "UA-39189505-1"

circos-version: "0.64"
circos-download-link: "http://circos.ca/distribution/circos-0.64.tgz"